#!/bin/sh
set -eu

if [ "$#" -lt 1 ]; then
    echo "usage: tinfoil-exec <container> [command...]" >&2
    exit 2
fi

container="$1"
shift

if [ "$#" -eq 0 ]; then
    set -- sh
fi

exec docker exec -it "$container" "$@"
