#!/bin/sh
set -eu

export HOME=/run/root
export DOCKER_HOST=unix:///var/run/docker.sock
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
cd "$HOME"

if [ "$#" -gt 0 ]; then
    exec /bin/busybox ash "$@"
fi

printf '\nTinfoil Containers Debug Shell (BusyBox v1.36.1 - ash)\nCheck README.md and AGENTS.md for more information.\n\n'
exec /usr/local/bin/block-winch /bin/busybox ash -l
